GOOGLE_API_KEY = "AIzaSyC3tT6zgDk1MzC7h-ToMSOGDermZj4y5b4"
[theme]
primaryColor = "#f63366"
# backgroundColor = "#10344b"
backgroundColor = "#111111"
# secondaryBackgroundColor = "#154360"
secondaryBackgroundColor = "#393939"
textColor = "#fafafa"
font = "sans serif"

[server]
enableStaticServing = true